(function(){
const PREP=window.SONAYELL_PREP_DATA||{};
const BASIC=window.SONAYELL_PREP_BASIC||[];
const EXTRA=window.SONAYELL_PREP_EXTRA||[];
if(!BASIC.length)return;
function ensure(){state.prepareV2Checks=state.prepareV2Checks||{};state.prepareV2Awarded=state.prepareV2Awarded||{};}
function count(k){ensure();return (state.prepareV2Checks[k]||[]).filter(Boolean).length;}
function complete(k){return count(k)===(PREP[k]?.items?.length||0);}
function total(){return BASIC.reduce((n,k)=>n+PREP[k].items.length,0);}
function checked(){return BASIC.reduce((n,k)=>n+count(k),0);}
function token(){return localStorage.getItem('sonayell_access_token')||'';}
function cfg(name){try{return parent.eval(name);}catch(e){return '';}}
async function rpc(name,body){const t=token(),u=cfg('SUPABASE_URL'),k=cfg('SUPABASE_KEY');if(!t||!u||!k)throw new Error('guest');const r=await fetch(u+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:k,Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify(body||{})});if(!r.ok)throw new Error(await r.text());const x=await r.text();return x?JSON.parse(x):null;}
async function loadServer(){if(!token())return;try{const rows=await rpc('sona_get_my_prepare_state',{});if(rows&&rows[0]){state.prepareV2Checks=rows[0].checks||{};state.prepareV2Awarded=rows[0].awarded||{};save();renderHome();renderCategories();}}catch(e){console.warn('prepare load',e);}}
async function persist(key){ensure();if(token()){try{const rows=await rpc('sona_save_my_prepare_state',{p_checks:state.prepareV2Checks,p_complete_key:key||null});if(rows&&rows[0]){state.prepareV2Awarded=rows[0].awarded||state.prepareV2Awarded;state.yell=Number(rows[0].yell)||state.yell;save();update();}}catch(e){console.warn('prepare save',e);alert('備えチェックを保存できませんでした。通信状態を確認して、もう一度試してね。');}}else{if(key&&!state.prepareV2Awarded[key]){state.prepareV2Awarded[key]=true;state.yell+=10;}save();update();}}
window.renderHome=function(){ensure();const all=total(),done=checked(),pct=all?done/all*100:0,text=document.getElementById('homeProgressText');if(!text)return;text.textContent=done+' / '+all;const bar=document.getElementById('homeProgressBar');if(bar)bar.style.width=pct+'%';const icon=document.getElementById('homeNextIcon'),title=document.getElementById('homeNextTitle'),badge=document.getElementById('homeNextBadge'),lead=document.getElementById('homeNextText'),button=document.getElementById('homeNextButton'),next=BASIC.find(k=>!complete(k));if(!next){icon.textContent='🎉';title.textContent='基本の備え COMPLETE！';badge.textContent=all+' / '+all+' 完了';lead.textContent='基本の備えがそろったよ。必要に応じて「わが家に必要な備え」も確認しよう。';button.textContent='我が家の備えを見る';button.onclick=()=>showScreen('prepareScreen');}else{icon.textContent=PREP[next].icon;title.textContent=done===0?'まずは「我が家の備え」から':'次は「'+PREP[next].name+'」をチェック';badge.textContent=done+' / '+all+' チェック';lead.textContent='下のカテゴリーから気になる備えを選んでね。一つずつチェックしながら、我が家の備えを進めていこう！✨';button.textContent='備えをチェックする';button.onclick=()=>showScreen('prepareScreen');}renderMyTree();};
window.renderCategories=function(){ensure();const list=document.getElementById('categoryList');if(!list)return;list.innerHTML='';const intro=document.createElement('div');intro.style.cssText='background:#fff;border-radius:18px;padding:14px;margin-bottom:12px;line-height:1.7;font-size:13px;color:#527056';intro.innerHTML='<strong style="color:#397a44">🏠 基本の備え '+checked()+' / '+total()+'</strong><br>下のカテゴリーから気になる備えを選んでね。<br>一つずつチェックしながら、我が家の備えを進めていこう！✨';list.appendChild(intro);function add(k){const p=PREP[k],n=count(k),ok=complete(k),b=document.createElement('button');b.className='categoryButton';b.onclick=()=>openCheck(k);b.innerHTML='<div class="categoryIcon">'+p.icon+'</div><div style="flex:1"><div class="categoryName">'+p.name+(ok?' ✅':'')+'</div><div class="categoryDescription">'+p.desc+'　'+n+' / '+p.items.length+(state.prepareV2Awarded[k]?'　🌟+10獲得済':'')+'</div></div><div style="font-size:22px">›</div>';list.appendChild(b);}BASIC.forEach(add);const h=document.createElement('div');h.style.cssText='margin:22px 2px 8px;font-weight:bold;color:#397a44';h.textContent='➕ わが家に必要な備え';list.appendChild(h);const note=document.createElement('div');note.style.cssText='font-size:12px;color:#78907a;line-height:1.6;margin:0 3px 10px';note.textContent='該当するものだけ選んでね。追加カテゴリーは基本74項目の達成率には影響しません。';list.appendChild(note);EXTRA.forEach(add);const pt=document.getElementById('overallProgressText');if(pt)pt.textContent=checked()+' / '+total();const pb=document.getElementById('overallProgressBar');if(pb)pb.style.width=(checked()/total()*100)+'%';};
window.openCheck=function(k){ensure();current=k;const p=PREP[k],list=document.getElementById('checkList'),saved=state.prepareV2Checks[k]||[];document.getElementById('checkTitle').textContent=p.icon+' '+p.name+'の備え';list.innerHTML='';p.items.forEach((item,i)=>{const c=document.createElement('div');c.className='checkCard';c.innerHTML='<label class="checkLabel"><input class="checkBox" type="checkbox" data-i="'+i+'" '+(saved[i]?'checked':'')+'><span>'+item+'</span></label>';c.querySelector('input').addEventListener('change',window.check);list.appendChild(c);});const m=document.getElementById('completeMessage');m.innerHTML=state.prepareV2Awarded[k]?'🎉 '+p.name+' COMPLETE！<br><br>🌟 初回COMPLETEの10 YELLは獲得済み':'🎉 '+p.name+' COMPLETE！<br>我が家の備えがまた一歩進んだよ！<br><br>🌱 YELL +10';m.classList.toggle('show',complete(k));showScreen('checkScreen');};
window.check=async function(){ensure();const boxes=[...document.querySelectorAll('#checkList .checkBox')];state.prepareV2Checks[current]=boxes.map(x=>x.checked);const all=boxes.length&&boxes.every(x=>x.checked),first=all&&!state.prepareV2Awarded[current];save();renderCategories();renderHome();await persist(first?current:null);if(first&&state.prepareV2Awarded[current]&&typeof leaf==='function')leaf();const m=document.getElementById('completeMessage');if(all){m.innerHTML='🎉 '+PREP[current].name+' COMPLETE！<br>我が家の備えがまた一歩進んだよ！<br><br>🌟 +10 YELL '+(state.prepareV2Awarded[current]?'獲得済み':'');m.classList.add('show');}else m.classList.remove('show');update();};
ensure();const lead=document.querySelector('#prepareScreen .pageLead');if(lead)lead.innerHTML='下のカテゴリーから気になる備えを選んでね。<br>一つずつチェックしながら、我が家の備えを進めていこう！✨';renderHome();renderCategories();loadServer();
})();